### PR TITLE
Add traffic plugin

### PR DESCRIPTION
**Pull request by michalslaski**

### CODE REVIEW

**Comment by arkgil** [comment]
traffic-1

👍

**Comment by arkgil** [comment]
@michalslaski would it be possible to show traffic to and from Internet, not only between Erlang nodes? If I tested correctly, when I monitor node which is not part of a cluster, traffic tab is empty. If not before EEF, I think it'd be nice feature anyway.

**Review by arkgil — APPROVED** [review]

**Comment by mentels** [comment]
It works 👍

**Review by mentels — APPROVED** [review]
The only thing that is missing is that you have to know that the `erlangpl-ui` is a git submodule and providing you had the repo already pulled down, you need to invoke `git submodule update --init --recursive` to get the submodule.

**Comment by baransu** [comment]
@mentels It's mentioned in https://github.com/erlanglab/erlangpl#getting-started
We didn't released `erlangpl-ui` 0.2 so you had to pull it manually. I'm trying to think about better solution for building UI within `erlangpl`. If you have any ideas let me know 🙂

**Comment by baransu** [comment]
#### GREAT WORK @michalslaski!!! 

How can I force reasonable amount of messages between two nodes to test how it works?

If I understand correctly, because of Vizceral limitations you're changing color (grey/yellow) to show messages from/to connected node? I'll try to do more research about showing messages in two directions.

/ cc @mentels @arkgil

**Review by baransu — APPROVED** [review]

**Comment by baransu** [comment]
I've added `"denamification"` to node/pid names. Unfortunately url is not `"denamificated"` at this moment but I'll change it in the future.

https://github.com/erlanglab/erlangpl-ui/blob/traffic-view/src/plugins/epl-vizceral/components/TrafficTools.js#L8

**Comment by mentels** [comment]
@Baransu it is possible to use `hooks` with rebar. Here's an example: https://github.com/ivanos/dobby_allinone_node/blob/master/rebar.config#L27

I believe rebar3 supports them as well.

**Comment by baransu** [comment]
Awesome @mentels! 
I'll try to adjust our build pipeline then to remove submodule.

**Comment by mentels** [comment]
I'm not saying that a submodule is worse that a `raw` rebar dependency :)

**Comment by baransu** [comment]
I know but personally I don't like current solution with submodule. I'd rather have tag/hash stored in some config file and then check if config is different than existing local version, if different then pull, update dependencies and rebuild. We can event make shell script or something like that and run it when during `make build-ui`. It could be nice to have `npm` fallback if `yarn` is not available or show some warns about missing `elm-lang` etc.

**Comment by michalslaski** [comment]
@Baransu you can generate messages between nodes by querying a distributed database Mnesia. 

To setup a Mnesia cluster, start several Erlang nodes with unique names e.g. a@, b@, c@, etc. and start the database on all of them:
```
erl -name a@127.0.0.1
(a@127.0.0.1)1> mnesia:start().
```

Then create a test_table and configure it to be replicated on all nodes:
```
(a@127.0.0.1)2> mnesia:change_config(extra_db_nodes, ['b@127.0.0.1']).
(a@127.0.0.1)3> mnesia:change_config(extra_db_nodes, ['c@127.0.0.1']).
(a@127.0.0.1)4> mnesia:change_config(extra_db_nodes, ['d@127.0.0.1']).
(a@127.0.0.1)5> mnesia:create_table(test_table, []).
(a@127.0.0.1)6> [mnesia:add_table_copy(test_table, Node, ram_copies) || Node <- nodes()].
```

Videos from the following experiments were posted on [YouTube](https://www.youtube.com/channel/UCGkcbu799cC1rtMaQtAajpg)

```
[begin mnesia:transaction(fun() -> mnesia:write({test_table, Key, "value"}) end), timer:sleep(10) end || Key <- lists:seq(1,2000)].
[begin mnesia:sync_dirty(fun() -> mnesia:write({test_table, Key, "value"}) end), timer:sleep(10) end || Key <- lists:seq(1,2000)].
[begin mnesia:dirty_write({test_table, Key, "value"}), timer:sleep(10) end || Key <- lists:seq(1,2000)].
```

**Comment by baransu** [comment]
I have problems with `mnesia` setup:

```
(c@127.0.0.1)2> mnesia:start().
ok
(c@127.0.0.1)3> mnesia:change_config(extra_db_nodes, 'b@127.0.0.1').
{error,{badarg,extra_db_nodes}}
```

**Comment by mentels** [comment]
@Baransu try 
`mnesia:change_config(extra_db_nodes, ['b@127.0.0.1']). # I've used a list`

**Comment by baransu** [comment]
It's beautiful 😍

image

**Pull request merged**
