### PR TITLE
Merge erlangpl-ui into erlangpl

### PR DESCRIPTION
**Pull request by baransu**
I've merged `erlangpl-ui` into `ui` folder within `erlangpl` repo. I don't know if subdirectory is good solution. I would rather merge it into root directory because we don't have any naming conflicts and it would simplify building, developing and probably other things. What do you think?

What should we do with old repo? Delete or keep it with deprecation note?

### CODE REVIEW

**Comment by baransu** [comment]
I've moved `package.json` to root directory to allow `yarn` command without switching directories. It also simplify `make` command. What do you think?

**Comment by arkgil** [comment]
I think that's fine. I'd also keep ui in subdirectory, it'll make things a little bit cleaner. Thanks for taking care of that!

**Comment by baransu** [comment]
@arkgil @michalslaski what should we do with old UI repo?

**Comment by arkgil** [comment]
We can make it private or delete it. We may also deprecate it for a little while, and delete it later.

**Comment by baransu** [comment]
Waiting for @michalslaski's review, and after that I think we can merge! 🎉

**Comment by michalslaski** [comment]
@Baransu I can review early next week,  but don't wait for it. Feel free to merge now, so that you can progress with new developments.

**Comment by baransu** [comment]
Awesome, going to merge later today 🎉🎊

**Review by arkgil — APPROVED** [review]

**Pull request merged**
