### PR TITLE
Change JSON library to jsone, add JSON encoding/decoding API

### PR DESCRIPTION
**Pull request by arkgil**
Basically swapped `ej` with `jsone` (also had to tune jsone a bit, add support for pids, ports, refs, funs and multi element tuples). Now all JSON encoding and decoding should happen using `epl_json:encode/2` and `epl_json:decode/1`.

### CODE REVIEW

**Comment by arkgil** [comment]
@michalslaski I am not sure how this affects buliding a "release" escript (although local builds with `make` and `./bootstrap` work fine). Im 99% sure it breaks `epl_3d` plugin.

**Comment by arkgil** [comment]
@Baransu I'm going to merge that one. API changes involve:
* `epl:proplist_to_json/2` changed to `epl_json:encode/2` (the same arguments)
    * this functions also accepts maps, so we can represent data as maps on Erlang side instead of proplists
* added `epl_json:decode/1` - decode JSON into maps

It is possible that shape of messages which come from `epl_dashboard` have changed a bit. Let me know if there is something to fix. Also with those changes `epl_3d` will be probably stop working.

**Comment by baransu** [comment]
I'm not using `epl_3d` during development right now. I'm waiting for more progress with this part of app to implement it on frontend.

I'll test current version of `erlangpl-ui` against this branch and I'll let you know.

**Comment by baransu** [comment]
@arkgil I found problem with `otp_release` and `version`. Previously these values were strings, right now they are number arrays.

image

**Comment by arkgil** [comment]
Ah, unfortunate encoding of charlists! I'll fix that.

**Comment by arkgil** [comment]
@Baransu would you be able to provide me a list of keys which are used in UI to displays system info and ERTS settings? I mean the keys from first payload sent to dashboard on websocket connection init.

EDIT: Or maybe I'll get myself comfortable with JS and dig into UI code a bit 🙂

**Comment by baransu** [comment]
Keys are run via `humps.camelizeKeys`to match JS naming convention.

https://github.com/erlanglab/erlangpl-ui/blob/master/src/home/components/SystemInfo.js#L9#L29

**Comment by arkgil** [comment]
Alright, should be fixed now. Let me know if everything works fine.

**Comment by baransu** [comment]
@arkgil It seems to looks fine.

**Comment by michalslaski** [comment]
@arkgil @Baransu let's not worry about epl_3d view for the time being. I'm very glad with the progress on all the refactorings as it will allow us to encode any Erlang terms and to build interesting views in the UI in the future.

The 3D visualization of a graph could be used to show spawns and exits, where vertex represents a process and edge represents parent-child relation between process spawning and process being spawned. I think such spawn-graph could help understand which parts of the system are extensively creating new processes. It could also help understand where most crashes happen. Overall it is an interesting area of performance analysis and I'm not sure it fits well other views we discussed so far, so I think it deserves a separate view.

We can get back to implementing it once we have dashboard, sup_tree and traffic views implemented and tested.

Many many thanks for your contributions so far!

**Pull request merged**
