### PR TITLE
Merge epl_st as in-umbrella application

### PR DESCRIPTION
**Pull request by arkgil**
As discussed in erlanglab/epl_st#8, we are merging epl_st application into main repository. After merging I'll tag version 0.6.1 🙂

### CODE REVIEW

**Comment by Baransu** [comment]
Can merge it preserving whole git history as I did with erlangpl-ui?

**Review by baransu — CHANGES_REQUESTED** [review]
Can you merge preserving git history
https://www.kernel.org/pub/software/scm/git/docs/howto/using-merge-subtree.html

**Comment by arkgil** [comment]
I have thought about that, but the history is 12 commits only and I thought it would be unnecessary mess.  Will do!

**Comment by baransu** [comment]
Maybe but let's keep consistency!

**Comment by arkgil** [comment]
Hm, but does it mean that epl_st will be handled as a different repository?

**Comment by baransu** [comment]
No, it's the same as UI. It will look like `epl_st` was always part of `erlangpl`. Check branch network for UI.

**Comment by arkgil** [comment]
Okay, that's nice. Anyway, I can't make the commands you provided work 😬

**Comment by baransu** [comment]
I'll do basic merge and you will continue from that point

**Comment by arkgil** [comment]
Thanks! Please post a comment later how did you make it work (so I learn how to do that 😅 ).

**Comment by baransu** [comment]
Opened as new PR #46

**Pull request closed without merging**
