### PR TITLE
[WIP] Integrate with new UI

### LINKED ISSUE #10: Integrating new UI
I'm doing research on adding `erlangpl-ui` as a new frontend. Only thing I need from backend is serving static folder at `localhost:8000` as it is right now.
I'll add `erlangpl-ui` as subrepo which will be fetched during build process and included in place of current UI.

Only thing I have problem understanding is how `erl_3d` is included in current frontend because plugin provides frontend as well. With new version it would be hard or impossible, and we're thinking about replacing it with 2nd or 3rd level view of vizceral. But having 3D visualization is nice and I can work on new version of 3D renderer for that which will be available at `/messages` within new UI. In that case `erl_3d` can only serve as backend plugin and all client code can be placed in `erlangpl-ui` or new repo.

What have to be done within this and `epl_3d` repo to provide new UI?

/ cc @michalslaski  @arkgil

### PR DESCRIPTION
**Pull request by baransu**
Resolve #10 

Introduces new UI. I've updated only `Makefile` to build new UI and move output to `apps/epl/priv/htdocs`. This way `bootsatrap` script can include it in bundle and application can serve static files. Only thing I have problem setting up is fallback to `/index.html` when route not found. This should be handled by frontend and server should redirect everything to `/index.html` 

/ cc @michalslaski @arkgil

### CODE REVIEW

**Comment by baransu** [comment]
I may have been doing something wrong because `erlangpl` output is 6.6MB large and @michalslaski got 1.7MB result.

**Comment by michalslaski** [comment]
I reduced the file size down to 1.7MB by not including the heavy .js.map file, fixed in https://github.com/erlanglab/erlangpl/commit/55a6a3d94b5f91871a5167854b6c6b0b42092831

**Comment by baransu** [comment]
Sourcemaps are good if you're opening browser DevTools with production site, and they are not downloaded until then. But yeah, we don't need then as part of the bundle.

**Comment by michalslaski** [comment]
If you need the .map files for debugging purposes, please see section about [running development release](https://github.com/erlanglab/erlangpl#running-development-release), which serves all files from the yarn build, when a browser tries to download them.

**Comment by baransu** [comment]
Awesome!

**Review by michalslaski — APPROVED** [review]
I'm happy with this PR and will merge. Thanks!

BTW, please check if fallback to index.html works as expected (see https://github.com/erlanglab/erlangpl/pull/14/commits/2c9a53ede941e3c69989bfba212a79ee255a71a3).

**Pull request merged**
